name: GitHub Actions Demo
on: [push]
jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Create firefox release
        run: cp manifest_firefox.json manifest.json ; zip -r uflix-next-button-firefox.zip ./* -x manifest_firefox.json manifest_chrome.json ; rm -f manifest.json
