name: Zip files to releases

on: 
  push:
    branches:
      -main

jobs:
  To-Zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Create firefox release
        run: cp manifest_firefox.json manifest.json ; zip -r uflix-next-button-firefox.zip ./* -x manifest_firefox.json manifest_chrome.json ; rm -f manifest.json ; ls

      - name: Commit and push
        run: git push
 
